# config/config.template.yaml

# Configuration settings template for the Bondit
# This file contains essential configuration parameters, including API keys and file paths,
# necessary for the proper functioning of the program.
# Copy this file to 'config.yaml' and replace the placeholder values with your actual data.

api:
  fred_api_key: "YOUR_FRED_API_KEY_HERE"
  # The API key for accessing the FRED (Federal Reserve Economic Data) API.
  # This key is required to fetch economic data from the FRED service.
  # Replace the placeholder value with your actual API key obtained from FRED.

storage:
  fred_file_path: "./data/fred_data.json"
  # The file path to the JSON file where the economic data retrieved from the FRED API
  # will be stored and cached. This path is used by the FredDataStorage class to save and
  # retrieve data. Adjust this path if you want to store the data in a different location
  # or with a different file name.

# Allocation Constraints:
# Defines the initial, minimum, and maximum allocation percentages for each asset type in the portfolio.
# - `initial`: The starting allocation percentage for the asset.
# - `min`: The minimum allowable allocation percentage to ensure sufficient exposure.
# - `max`: The maximum allowable allocation percentage to prevent overexposure.
# Each asset is accompanied by a comment describing its purpose within the portfolio. 
 
allocations:
  VBIRX:
    initial: 40.0
    min: 10.0
    max: 70.0
    # Vanguard Short-Term Bond Index Fund: Provides exposure to short-term investment-grade bonds.
  VBLAX:
    initial: 40.0
    min: 10.0
    max: 70.0
    # Vanguard Long-Term Bond Index Fund: Provides exposure to long-term investment-grade bonds.
  VTAPX:
    initial: 20.0
    min: 0.0
    max: 30.0
    # Vanguard Short-Term Inflation-Protected Securities Index Fund: Protects against inflation by investing in TIPS.