# config/config.template.yaml

# Configuration settings template for the Bondit
# This file contains essential configuration parameters, including API keys and file paths,
# necessary for the proper functioning of the program.
# Copy this file to 'config.yaml' and replace the placeholder values with your actual data.

api:
  fred_api_key: "YOUR_FRED_API_KEY_HERE"
  # The API key for accessing the FRED (Federal Reserve Economic Data) API.
  # This key is required to fetch economic data from the FRED service.
  # Replace the placeholder value with your actual API key obtained from FRED.

storage:
  fred_file_path: "./data/fred_data.json"
  # The file path to the JSON file where the economic data retrieved from the FRED API
  # will be stored and cached. This path is used by the FredDataStorage class to save and
  # retrieve data. Adjust this path if you want to store the data in a different location
  # or with a different file name.
  
  recommendation_file_path: "./data/recommendations_data.json"
  # The file path to the JSON file where investment recommendations generated by the
  # RecommendationEngine will be stored. This path is used by the RecommendationStorage
  # class to save and retrieve recommendations. Adjust this path if you want to store
  # the recommendations in a different location or with a different file name.

# Add any additional configuration sections or parameters below as needed for your project.